POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "Refactoring java code",
  "author": "Petri L.",
  "url": "becomefullstack.com",
  "likes": 1,
  "userId": "5e175bf20c393b0a768b60c7"
}