POST http://localhost:3000/api/blogs
Content-Type: application/json

{
  "title": "Refactoring java code part 2",
  "author": "Petri L.",
  "url": "becomefullstack.com",
  "likes": 1,
  "userId": "5e1b03ace6e176260accc85f"
}